name: "Bug Tracking Board"
description: "Track and manage bug reports and fixes"

fields:
  - name: "Status"
    type: "single_select"
    options:
      - name: "New"
        description: "Newly reported bugs awaiting triage"
        color: "red"
      - name: "Triaged"
        description: "Bugs that have been reviewed and prioritized"
        color: "yellow"
      - name: "In Progress"
        description: "Bugs currently being worked on"
        color: "blue"
      - name: "Testing"
        description: "Fixes ready for testing"
        color: "purple"
      - name: "Done"
        description: "Bugs that have been fixed and verified"
        color: "green"

  - name: "Priority"
    type: "single_select"
    options:
      - name: "Critical"
        description: "Blocks core functionality"
        color: "red"
      - name: "High"
        description: "Important but not blocking"
        color: "orange"
      - name: "Medium"
        description: "Standard priority"
        color: "yellow"
      - name: "Low"
        description: "Nice to have fixes"
        color: "green"

  - name: "Component"
    type: "single_select"
    options:
      - name: "Elements"
        description: "Element classes and properties"
      - name: "Molecules"
        description: "Molecule representation and manipulation"
      - name: "Database"
        description: "Data storage and retrieval"
      - name: "Quantum"
        description: "Quantum chemistry calculations"
      - name: "Visualization"
        description: "2D/3D molecular visualization"
      - name: "CLI"
        description: "Command-line interface"
      - name: "Documentation"
        description: "Documentation and tutorials"
      - name: "Infrastructure"
        description: "CI/CD, build, deployment"

views:
  - name: "All Bugs"
    type: "table"
    layout:
      - field: "title"
      - field: "Status"
      - field: "Priority"
      - field: "Component"
      - field: "assignees"
      - field: "labels"

  - name: "Active Bugs"
    type: "board"
    group_by: "Status"
    filter: "Status:New,Triaged,In Progress,Testing"

  - name: "By Priority"
    type: "board"
    group_by: "Priority"
    filter: "Status:New,Triaged,In Progress"