name: "Feature Development Board"
description: "Track feature requests and development progress"

fields:
  - name: "Status"
    type: "single_select"
    options:
      - name: "Proposed"
        description: "Feature requests awaiting review"
        color: "gray"
      - name: "Approved"
        description: "Features approved for development"
        color: "green"
      - name: "In Design"
        description: "Features being designed and planned"
        color: "yellow"
      - name: "In Development"
        description: "Features currently being implemented"
        color: "blue"
      - name: "In Review"
        description: "Features ready for code review"
        color: "purple"
      - name: "Testing"
        description: "Features being tested"
        color: "orange"
      - name: "Done"
        description: "Features completed and merged"
        color: "green"

  - name: "Size"
    type: "single_select"
    options:
      - name: "XS"
        description: "Very small feature (1-2 days)"
        color: "green"
      - name: "S"
        description: "Small feature (3-5 days)"
        color: "yellow"
      - name: "M"
        description: "Medium feature (1-2 weeks)"
        color: "orange"
      - name: "L"
        description: "Large feature (2-4 weeks)"
        color: "red"
      - name: "XL"
        description: "Extra large feature (1+ months)"
        color: "purple"

  - name: "Category"
    type: "single_select"
    options:
      - name: "Core Chemistry"
        description: "Element and molecule functionality"
      - name: "Quantum Chemistry"
        description: "Quantum calculations and methods"
      - name: "Visualization"
        description: "2D/3D molecular visualization"
      - name: "Database"
        description: "Data storage and retrieval"
      - name: "Machine Learning"
        description: "ML models and predictions"
      - name: "User Interface"
        description: "CLI, web interface, APIs"
      - name: "Performance"
        description: "Optimization and scalability"
      - name: "Integration"
        description: "External tool integration"

  - name: "Priority"
    type: "single_select"
    options:
      - name: "Must Have"
        description: "Critical for next release"
        color: "red"
      - name: "Should Have"
        description: "Important for next release"
        color: "orange"
      - name: "Could Have"
        description: "Nice to have if time permits"
        color: "yellow"
      - name: "Won't Have"
        description: "Not planned for current release"
        color: "gray"

views:
  - name: "All Features"
    type: "table"
    layout:
      - field: "title"
      - field: "Status"
      - field: "Priority"
      - field: "Size"
      - field: "Category"
      - field: "assignees"

  - name: "Development Pipeline"
    type: "board"
    group_by: "Status"
    filter: "Status:Approved,In Design,In Development,In Review,Testing"

  - name: "By Category"
    type: "board"
    group_by: "Category"
    filter: "Status:Proposed,Approved,In Design,In Development"

  - name: "Current Sprint"
    type: "table"
    filter: "Status:In Development,In Review,Testing"
    sort:
      - field: "Priority"
        direction: "desc"