name: "Release Management Board"
description: "Track release planning, milestones, and deployment progress"

fields:
  - name: "Status"
    type: "single_select"
    options:
      - name: "Planning"
        description: "Release being planned and scoped"
        color: "gray"
      - name: "In Progress"
        description: "Release development in progress"
        color: "blue"
      - name: "Feature Freeze"
        description: "No new features, bug fixes only"
        color: "yellow"
      - name: "Testing"
        description: "Release candidate testing"
        color: "orange"
      - name: "Ready"
        description: "Ready for deployment"
        color: "green"
      - name: "Released"
        description: "Successfully released"
        color: "purple"

  - name: "Release Type"
    type: "single_select"
    options:
      - name: "Major"
        description: "Breaking changes (x.0.0)"
        color: "red"
      - name: "Minor"
        description: "New features (0.x.0)"
        color: "blue"
      - name: "Patch"
        description: "Bug fixes (0.0.x)"
        color: "green"
      - name: "Hotfix"
        description: "Critical bug fixes"
        color: "orange"

  - name: "Priority"
    type: "single_select"
    options:
      - name: "Critical"
        description: "Security or critical bug fixes"
        color: "red"
      - name: "High"
        description: "Important features or fixes"
        color: "orange"
      - name: "Normal"
        description: "Regular release schedule"
        color: "yellow"
      - name: "Low"
        description: "Nice to have improvements"
        color: "green"

  - name: "Target Environment"
    type: "single_select"
    options:
      - name: "Development"
        description: "Development environment"
        color: "gray"
      - name: "Staging"
        description: "Staging environment"
        color: "yellow"
      - name: "Production"
        description: "Production environment"
        color: "green"

views:
  - name: "All Releases"
    type: "table"
    layout:
      - field: "title"
      - field: "Status"
      - field: "Release Type"
      - field: "Priority"
      - field: "Target Environment"
      - field: "assignees"
      - field: "milestone"

  - name: "Release Pipeline"
    type: "board"
    group_by: "Status"
    sort:
      - field: "Priority"
        direction: "desc"

  - name: "By Release Type"
    type: "board"
    group_by: "Release Type"
    filter: "Status:Planning,In Progress,Feature Freeze,Testing,Ready"

  - name: "Current Releases"
    type: "table"
    filter: "Status:In Progress,Feature Freeze,Testing,Ready"
    sort:
      - field: "Priority"
        direction: "desc"