import os

# Get the path to the element_data.py file
script_dir = os.path.dirname(os.path.abspath(__file__))
elements_dir = os.path.join(script_dir, "chemesty", "elements")

# Extract element symbols from element_data.py
element_symbols = []
with open(os.path.join(elements_dir, "element_data.py"), "r") as f:
    for line in f:
        if line.strip().startswith('"') and line.strip().endswith('": {'):
            # Extract the symbol from lines like '    "H": {'
            symbol = line.strip().strip('": {')
            element_symbols.append(symbol)

# Update __init__.py
with open(os.path.join(elements_dir, "__init__.py"), "w") as f:
    f.write("# This file is auto-generated by generate_elements.py\n\n")
    
    # Import all element classes
    for symbol in element_symbols:
        class_name = symbol.capitalize()
        f.write(f"from chemesty.elements.{symbol.lower()} import {class_name}\n")
    
    # Export all element classes
    f.write("\n__all__ = [\n")
    for symbol in element_symbols:
        class_name = symbol.capitalize()
        f.write(f"    '{class_name}',\n")
    f.write("]\n")

print(f"Updated {os.path.join(elements_dir, '__init__.py')}")